### ISSUE TITLE
License contains reference to FreeBSD project

### ISSUE THREAD

**Issue by cmriedl** [treycucco/vim-monotonic#1]
I don't think this is needed in your LICENSE unless this project is actually affiliated with FreeBSD:

`The views and conclusions contained in the software and documentation are those
of the authors and should not be interpreted as representing official policies,
either expressed or implied, of the FreeBSD Project.`

**Comment by treycucco** [comment]
@wrwlf you're right. I copy pasta'd the license at some point and didn't clean it up properly, that's probably in some of my other projects too. Thanks for the heads up!
